### PR TITLE
Fixed Clip Review breaking on invalid user image

### PR DESCRIPTION
**Pull request by Bensikrac**
## **Description**
- fixed issue described here: https://discord.com/channels/903349717323382814/1096839104139894936

- [X] I have read the [Contributing Guide](https://docs.waldo.vision/en/getting-started/), and agree to follow the [Code of Conduct](https://docs.waldo.vision/legal/code-of-conduct/).

### CODE REVIEW

**Comment by Bensikrac** [comment]
Idk if reviewItem.user.image as string is needed or it suffices without that, since in db it is already as string

**Comment by Bensikrac** [comment]
And what about using a dummy image, since it works, but complains in console that no src url is specified if image is ''

**Comment by Huskydog9988** [comment]
I think using a default image would probably be for the best, as thats what we do for battle.net https://github.com/waldo-vision/waldo/blob/master/apps/web/auth-providers/battlenet.ts#L31

**Comment by Bensikrac** [comment]
which image should it be?

**Comment by Huskydog9988** [comment]
Personally I think just using the battle.net image is fine.

**Comment by Bensikrac** [comment]
Ok added it. I also needed to add waldo.vision to the list of allowed image sites.

**Review by Huskydog9988 — APPROVED** [review]

**Pull request merged**
